# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b996455df81514f1a3120850a66d6e2528fd5925b97deca2f4975dc4c031d994c5b467887a36b5bc7d8b2da76020c63c863eb017ecf538145e18ecd804476db

test:
  secret_key_base: 0c8a576508413727b1c4d4c1fb30f1e1192f70a25e3a3d0fc210cf937d2cb688418696171b2ffc2458cb5af5911a1feb826b9742c8c4d8db247f9637dd124d01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
